"""add_cascade_delete

Revision ID: 2862dbb9d305
Revises: f000a9dda83a
Create Date: 2026-06-14 14:43:44.708405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2862dbb9d305'
down_revision: Union[str, None] = 'f000a9dda83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('health_check_logs_endpoint_id_fkey', 'health_check_logs', type_='foreignkey')
    op.create_foreign_key('health_check_logs_endpoint_id_fkey', 'health_check_logs', 'monitored_endpoints', ['endpoint_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('incidents_endpoint_id_fkey', 'incidents', type_='foreignkey')
    op.create_foreign_key('incidents_endpoint_id_fkey', 'incidents', 'monitored_endpoints', ['endpoint_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('monitored_endpoints_owner_user_id_fkey', 'monitored_endpoints', type_='foreignkey')
    op.create_foreign_key('monitored_endpoints_owner_user_id_fkey', 'monitored_endpoints', 'users', ['owner_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('monitored_endpoints_owner_user_id_fkey', 'monitored_endpoints', type_='foreignkey')
    op.create_foreign_key('monitored_endpoints_owner_user_id_fkey', 'monitored_endpoints', 'users', ['owner_user_id'], ['id'])
    op.drop_constraint('incidents_endpoint_id_fkey', 'incidents', type_='foreignkey')
    op.create_foreign_key('incidents_endpoint_id_fkey', 'incidents', 'monitored_endpoints', ['endpoint_id'], ['id'])
    op.drop_constraint('health_check_logs_endpoint_id_fkey', 'health_check_logs', type_='foreignkey')
    op.create_foreign_key('health_check_logs_endpoint_id_fkey', 'health_check_logs', 'monitored_endpoints', ['endpoint_id'], ['id'])
    # ### end Alembic commands ###
